import { StyleSheet, Dimensions, StatusBar } from 'react-native';
import { Colors, Typography, Spacing, Radii } from '../../theme';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.dominant,
  },
  map: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: Colors.dominant,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
  },
  loadingText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeMD,
    color: Colors.text,
    marginTop: Spacing.md,
  },
  loaderGrid: {
    width: 45,
    height: 45,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignContent: 'space-between',
  },
  loaderSquare: {
    width: 20,
    height: 20,
    borderWidth: 2,
    borderColor: '#fe893e',
    backgroundColor: 'transparent',
  },
  
  // HUD Overlays
  topHudContainer: {
    position: 'absolute',
    top: StatusBar.currentHeight ? StatusBar.currentHeight + 8 : 44,
    left: Spacing.md,
    right: Spacing.md,
    zIndex: 10,
    gap: Spacing.sm,
  },
  
  topRightControls: {
    position: 'absolute',
    top: StatusBar.currentHeight ? StatusBar.currentHeight + 4 : 24,
    right: Spacing.md,
    zIndex: 20,
    gap: 12,
  },
  sidebarContainer: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: 300,
    zIndex: 100,
    flexDirection: 'row',
  },
  sidebarContent: {
    flex: 1,
    backgroundColor: Colors.white,
    paddingTop: StatusBar.currentHeight ? StatusBar.currentHeight + Spacing.lg : 60,
    paddingHorizontal: Spacing.lg,
    borderRightWidth: 1,
    borderRightColor: 'rgba(0,0,0,0.1)',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 10,
  },
  sidebarToggleBtn: {
    position: 'absolute',
    right: -48,
    top: StatusBar.currentHeight ? StatusBar.currentHeight + 24 : 64,
    width: 48,
    height: 48,
    backgroundColor: Colors.white,
    borderTopRightRadius: 12,
    borderBottomRightRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 0 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 8,
  },
  hudButton: {
    width: 72,
    height: 72,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hudBadge: {
    position: 'absolute',
    top: 4,
    right: 4,
    backgroundColor: Colors.accent,
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: Colors.dominant,
  },
  hudBadgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
  },
  
  // Toggle Explore / Treasure Hunt
  modeToggleWrapper: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderRadius: Radii.full,
    padding: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
    alignSelf: 'center',
    marginBottom: Spacing.sm,
  },
  modeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: Radii.full,
    gap: 6,
  },
  modeBtnActive: {
    backgroundColor: Colors.secondary,
  },
  modeBtnText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeSM,
    color: Colors.text,
  },
  modeBtnTextActive: {
    color: Colors.white,
    fontWeight: '700',
  },

  // Monthly Event Card
  monthlyEventCard: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: Radii.lg,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: 'rgba(254, 137, 62, 0.3)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  monthlyDateText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeXS,
    color: Colors.secondary,
    letterSpacing: 1,
  },
  monthlyTitleText: {
    fontFamily: Typography.fontDisplay,
    fontSize: Typography.sizeMD,
    color: Colors.text,
    fontWeight: '700',
  },

  // Treasure Hunt Card
  huntCard: {
    backgroundColor: 'rgba(15, 92, 92, 0.95)',
    borderRadius: Radii.lg,
    padding: Spacing.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  huntHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  huntTitle: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeXS,
    color: '#ACEEEE',
    letterSpacing: 0.5,
    fontWeight: '700',
  },
  huntProgress: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeXS,
    color: Colors.white,
  },
  huntClueText: {
    fontFamily: Typography.fontBody,
    fontSize: Typography.sizeSM,
    color: Colors.white,
    lineHeight: 20,
  },
  
  // Markers
  regionMarker: {
    backgroundColor: 'rgba(255,255,255,0.9)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: Radii.md,
    borderWidth: 1,
    borderColor: 'rgba(15,92,92,0.2)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
  },
  regionMarkerText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeSM,
    color: Colors.text,
    fontWeight: '700',
  },
  areaMarker: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  areaIconWrapper: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: Colors.secondary,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 5,
  },
  areaIconWrapperEvent: {
    borderColor: Colors.accent,
    backgroundColor: '#FFF5F0',
  },
  areaIconText: {
    fontSize: 20,
  },
  areaLabel: {
    marginTop: 4,
    backgroundColor: 'rgba(255,255,255,0.85)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    fontFamily: Typography.fontBodyMed,
    fontSize: 10,
    color: Colors.text,
  },
  
  // Back to Sri Lanka Map Btn
  backToCountryBtn: {
    position: 'absolute',
    bottom: Spacing.xl,
    alignSelf: 'center',
    backgroundColor: Colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: Radii.full,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
    zIndex: 20,
  },
  backToCountryText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeSM,
    color: Colors.text,
    fontWeight: '700',
  },

  // Bottom Sheet
  sheetContentWrapper: {
    flex: 1,
    paddingBottom: Spacing.lg,
  },
  sheetHeroImage: {
    width: '100%',
    height: 160,
    borderRadius: Radii.lg,
    marginBottom: Spacing.lg,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  filterSheetTitle: {
    fontFamily: Typography.fontDisplay,
    fontSize: Typography.sizeXL,
    color: Colors.text,
    marginBottom: Spacing.lg,
  },
  filterItem: {
    paddingVertical: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.05)',
  },
  filterItemText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeMD,
    color: Colors.text,
  },
  sheetRegion: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeXS,
    color: Colors.secondary,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  sheetTitle: {
    fontFamily: Typography.fontDisplay,
    fontSize: 24,
    color: Colors.text,
    fontWeight: '700',
    marginBottom: Spacing.md,
  },
  sheetDescription: {
    fontFamily: Typography.fontBody,
    fontSize: Typography.sizeSM,
    color: Colors.textMuted,
    lineHeight: 22,
    marginBottom: Spacing.lg,
  },
  sheetStats: {
    flexDirection: 'row',
    gap: Spacing.md,
    marginBottom: Spacing.xl,
  },
  statBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F7F5',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: Radii.md,
    gap: 6,
  },
  statText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeSM,
    color: Colors.text,
  },
  exploreBtn: {
    backgroundColor: Colors.secondary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    borderRadius: Radii.lg,
    gap: 8,
    shadowColor: Colors.secondary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  exploreBtnText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeMD,
    color: Colors.white,
    fontWeight: '700',
  },
  
  // Treasure Found UI
  treasureFoundContainer: {
    alignItems: 'center',
    padding: Spacing.lg,
  },
  treasureTitle: {
    fontFamily: Typography.fontDisplay,
    fontSize: 24,
    color: Colors.accent,
    fontWeight: '700',
    marginTop: Spacing.md,
    marginBottom: Spacing.sm,
  },
  treasureReward: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeMD,
    color: Colors.text,
    marginBottom: Spacing.lg,
  }
});
