import { StyleSheet } from 'react-native';
import { Colors, Typography, Spacing, Radii } from '../../theme';

export const styles = StyleSheet.create({
  container: {
    paddingHorizontal: Spacing.md,
    marginBottom: Spacing.lg,
  },
  knowledgeCard: {
    backgroundColor: Colors.secondary,
    borderRadius: Radii.xl,
    padding: Spacing.md,
    position: 'relative',
    overflow: 'hidden',
    elevation: 3,
  },
  knowledgeGlowTop: {
    position: 'absolute',
    top: -40,
    right: -40,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(15, 92, 92, 0.4)',
  },
  knowledgeGlowBottom: {
    position: 'absolute',
    bottom: -30,
    left: -30,
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: Colors.accentSubtle,
  },
  knowledgeCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.sm,
  },
  knowledgeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  knowledgeBadgeText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: 11,
    color: '#ACEEEE',
    letterSpacing: 0.8,
    fontWeight: '600',
  },
  followBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#fe893e',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#fe893e',
  },
  followingBtn: {
    backgroundColor: 'rgba(254, 137, 62, 0.25)',
    borderColor: 'rgba(254, 137, 62, 0.5)',
  },
  followBtnText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeSM,
    color: '#ffffff',
    fontWeight: '700',
  },
  followingBtnText: {
    color: '#fe893e',
  },
  knowledgeProfileRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
    marginBottom: Spacing.sm,
  },
  knowledgeAvatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: '#ACEEEE',
  },
  knowledgeInfo: {
    flex: 1,
  },
  knowledgeName: {
    fontFamily: Typography.fontDisplay,
    fontSize: Typography.sizeLG,
    fontWeight: '700',
    color: Colors.white,
    marginBottom: 2,
  },
  knowledgeTitle: {
    fontFamily: Typography.fontBody,
    fontSize: Typography.sizeXS,
    color: '#ACEEEE',
    marginBottom: 6,
  },
  knowledgeTag: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: Radii.sm,
    borderWidth: 1,
    borderColor: 'rgba(172, 238, 238, 0.25)',
  },
  knowledgeTagText: {
    fontFamily: Typography.fontBody,
    fontSize: 10,
    color: '#ACEEEE',
  },
  knowledgeQuote: {
    fontFamily: Typography.fontDisplay,
    fontSize: Typography.sizeMD,
    fontStyle: 'italic',
    color: 'rgba(255, 255, 255, 0.95)',
    borderLeftWidth: 3,
    borderLeftColor: Colors.accent,
    paddingLeft: Spacing.sm,
    marginVertical: Spacing.xs,
    lineHeight: 22,
  },
  knowledgeFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.15)',
    paddingTop: Spacing.sm,
    marginTop: Spacing.sm,
  },
  knowledgeActionText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeXS,
    color: '#ACEEEE',
  },
});
