import { StyleSheet, Dimensions } from 'react-native';
import { Colors, Typography, Spacing } from '../../../theme';

export const styles = StyleSheet.create({
  flex1: { flex: 1, backgroundColor: '#f8faf9' },
  rowCenter: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  fullImg: { width: '100%', height: '100%', resizeMode: 'cover' },
  
  headerOverlay: { position: 'absolute', top: 0, left: 0, right: 0, zIndex: 50, backgroundColor: 'transparent', borderBottomWidth: 0 },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', height: 64, paddingHorizontal: Spacing.md },
  iconBtn: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(0,0,0,0.4)' },
  headerTitle: { fontFamily: Typography.fontDisplay, fontSize: Typography.sizeMD, fontWeight: '700', color: Colors.white, textShadowColor: 'rgba(0,0,0,0.5)', textShadowOffset: { width: 0, height: 1 }, textShadowRadius: 3 },

  scrollContent: { paddingTop: 0, paddingBottom: 100 },
  
  heroVideo: { width: '100%', height: Dimensions.get('window').height * 0.45, backgroundColor: '#000', overflow: 'hidden' },
  heroImg: { width: '100%', height: '100%', opacity: 0.8 },
  videoOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.3)', padding: 16, justifyContent: 'space-between' },
  topActionsRow: { flexDirection: 'row', gap: 8 },
  smallIconBtn: { padding: 8, backgroundColor: 'rgba(0,0,0,0.4)', borderRadius: 20 },
  centerPlayBtnBox: { alignItems: 'center', justifyContent: 'center' },
  playBtnLarge: { width: 64, height: 64, borderRadius: 32, backgroundColor: 'rgba(0, 67, 67, 0.8)', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)' },
  bottomControls: { gap: 12 },
  progressBarBg: { height: 6, backgroundColor: 'rgba(255,255,255,0.3)', borderRadius: 3, width: '100%' },
  progressBarFill: { height: '100%', width: '40%', backgroundColor: '#aceeee', borderRadius: 3, position: 'relative' },
  progressHandle: { position: 'absolute', right: -4, top: -3, width: 12, height: 12, borderRadius: 6, backgroundColor: Colors.white },
  timeRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  timeText: { fontFamily: Typography.fontBodyMed, fontSize: 11, color: Colors.white, fontWeight: '600' },
  ccBox: { flexDirection: 'row', alignItems: 'center', gap: 4, opacity: 0.8 },
  ccText: { fontFamily: Typography.fontBodyMed, fontSize: 11, color: Colors.white },

  contentBody: { paddingHorizontal: Spacing.md, paddingTop: Spacing.md, backgroundColor: '#f8faf9', zIndex: 10 },
  
  titleSection: { gap: 12, marginBottom: Spacing.md },
  tagBadge: { alignSelf: 'flex-start', backgroundColor: 'rgba(254, 137, 62, 0.1)', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, borderWidth: 1, borderColor: 'rgba(254, 137, 62, 0.2)' },
  tagBadgeText: { fontFamily: Typography.fontBodyMed, fontSize: 10, fontWeight: '700', color: Colors.accent, textTransform: 'uppercase' },
  mainTitle: { fontFamily: Typography.fontDisplay, fontSize: 28, fontWeight: '600', color: Colors.text, lineHeight: 36 },
  metaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 16 },
  metaItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  metaText: { fontFamily: Typography.fontBodyMed, fontSize: 12, color: Colors.textMuted },

  actionRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 16, borderTopWidth: 1, borderBottomWidth: 1, borderColor: 'rgba(191, 200, 200, 0.2)', marginBottom: Spacing.lg },
  actionBtn: { flex: 1, alignItems: 'center', gap: 6 },
  actionBtnTextDark: { fontFamily: Typography.fontBodyMed, fontSize: 12, fontWeight: '600', color: Colors.text },
  actionBtnText: { fontFamily: Typography.fontBodyMed, fontSize: 12, fontWeight: '600', color: Colors.textMuted },

  section: { marginBottom: Spacing.lg },
  sectionSubhead: { fontFamily: Typography.fontBodyMed, fontSize: 12, fontWeight: '600', color: Colors.textMuted, textTransform: 'uppercase', marginBottom: 16, letterSpacing: 1 },
  horizontalScroll: { gap: 12, paddingBottom: 16 },
  chapterCardActive: { width: 120, backgroundColor: '#f2f4f3', padding: 12, borderRadius: 12, borderWidth: 1, borderColor: 'rgba(0, 67, 67, 0.2)' },
  chapterCard: { width: 120, backgroundColor: Colors.white, padding: 12, borderRadius: 12, borderWidth: 1, borderColor: 'rgba(191, 200, 200, 0.3)' },
  chapterProgressBg: { height: 6, backgroundColor: 'rgba(0, 67, 67, 0.2)', borderRadius: 3, marginBottom: 8 },
  chapterProgressFill: { width: '100%', height: '100%', backgroundColor: Colors.secondary, borderRadius: 3 },
  chapterTitleActive: { fontFamily: Typography.fontBodyMed, fontSize: Typography.sizeSM, fontWeight: '700', color: Colors.secondary },
  chapterTitle: { fontFamily: Typography.fontBodyMed, fontSize: Typography.sizeSM, fontWeight: '600', color: Colors.text },
  chapterTimeActive: { fontFamily: Typography.fontBodyMed, fontSize: 11, color: Colors.secondary, marginTop: 4 },
  chapterTime: { fontFamily: Typography.fontBodyMed, fontSize: 11, color: Colors.textMuted, marginTop: 4 },

  profileCard: { backgroundColor: '#f2f4f3', padding: Spacing.md, borderRadius: 16, borderWidth: 1, borderColor: 'rgba(191, 200, 200, 0.2)', overflow: 'hidden' },
  profileDeco: { position: 'absolute', right: -48, top: -48, width: 160, height: 160, borderRadius: 80, backgroundColor: 'rgba(15, 92, 92, 0.05)' },
  rowCenterHead: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: Spacing.sm },
  profileHeadText: { fontFamily: Typography.fontBodyMed, fontSize: 12, fontWeight: '700', color: Colors.secondary, letterSpacing: 1 },
  profileInfoRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: Spacing.sm },
  profileAvatarBox: { width: 80, height: 80, borderRadius: 40, borderWidth: 4, borderColor: '#f8faf9', overflow: 'hidden' },
  profileName: { fontFamily: Typography.fontDisplay, fontSize: Typography.sizeMD, fontWeight: '600', color: Colors.text, marginBottom: 4 },
  profileRole: { fontFamily: Typography.fontBodyMed, fontSize: 12, color: Colors.textMuted, fontWeight: '500' },
  quoteBox: { position: 'relative', paddingLeft: 24, paddingTop: 8 },
  quoteMark: { position: 'absolute', top: 0, left: 0, fontFamily: Typography.fontDisplay, fontSize: 48, color: 'rgba(0, 67, 67, 0.1)', lineHeight: 48 },
  quoteText: { fontFamily: Typography.fontBody, fontSize: 18, color: Colors.textMuted, fontStyle: 'italic', lineHeight: 28 },

  interactiveBtn: { backgroundColor: Colors.secondary, borderRadius: 16, padding: Spacing.md, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  interactiveLeft: { flex: 1, gap: 4 },
  interactiveRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  interactiveTag: { fontFamily: Typography.fontBodyMed, fontSize: 11, color: '#aceeee', fontWeight: '700', letterSpacing: 1 },
  interactiveTitle: { fontFamily: Typography.fontDisplay, fontSize: 24, fontWeight: '700', color: Colors.white },
  interactiveRight: { width: 48, height: 48, borderRadius: 24, backgroundColor: 'rgba(255,255,255,0.1)', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)' },

  contextHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: Spacing.sm },
  contextLine: { width: 6, height: 24, backgroundColor: Colors.accent, borderRadius: 3 },
  sectionTitle: { fontFamily: Typography.fontDisplay, fontSize: 24, fontWeight: '600', color: Colors.text },
  contextBody: { padding: Spacing.md },
  bodyText: { fontFamily: Typography.fontBody, fontSize: Typography.sizeSM, color: Colors.textMuted, lineHeight: 24 },
  boldText: { fontWeight: '600', color: Colors.text },

  bentoRow: { flexDirection: 'row', gap: 12 },
  bentoCardSmall: { flex: 1, backgroundColor: '#f2f4f3', padding: 16, borderRadius: 16, borderWidth: 1, borderColor: 'rgba(191, 200, 200, 0.3)' },
  bentoIconPrimary: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(0, 67, 67, 0.1)', alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  bentoIconSecondary: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(254, 137, 62, 0.1)', alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  bentoTitle: { fontFamily: Typography.fontBodyMed, fontSize: Typography.sizeSM, fontWeight: '700', color: Colors.text },
  bentoDesc: { fontFamily: Typography.fontBodyMed, fontSize: 12, color: Colors.textMuted, marginTop: 2 },
  
  bentoCardFull: { backgroundColor: '#f2f4f3', padding: 16, borderRadius: 16, borderWidth: 1, borderColor: 'rgba(191, 200, 200, 0.3)', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  bentoCardFullLeft: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  bentoIconTertiary: { width: 48, height: 48, borderRadius: 12, backgroundColor: 'rgba(54, 60, 66, 0.1)', alignItems: 'center', justifyContent: 'center' },

  quizCard: { backgroundColor: 'rgba(255, 219, 201, 0.2)', padding: Spacing.md, borderRadius: 24, borderWidth: 1, borderColor: 'rgba(155, 70, 0, 0.2)', overflow: 'hidden' },
  quizDeco: { position: 'absolute', right: -24, top: -24, width: 128, height: 128, borderRadius: 64, backgroundColor: 'rgba(155, 70, 0, 0.05)' },
  quizHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: Spacing.sm, zIndex: 10 },
  quizTitle: { fontFamily: Typography.fontDisplay, fontSize: Typography.sizeMD, fontWeight: '700', color: Colors.text },
  xpBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: Colors.white, paddingHorizontal: 12, paddingVertical: 4, borderRadius: 16, borderWidth: 1, borderColor: 'rgba(155, 70, 0, 0.1)' },
  xpBadgeText: { fontFamily: Typography.fontBodyMed, fontSize: 11, fontWeight: '700', color: Colors.accent },
  quizQuestion: { fontFamily: Typography.fontBody, fontSize: Typography.sizeSM, color: Colors.textMuted, marginBottom: 24, zIndex: 10 },
  quizOptions: { gap: 12, zIndex: 10 },
  quizOptionBtn: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16, backgroundColor: Colors.white, borderRadius: 12, borderWidth: 1, borderColor: 'rgba(191, 200, 200, 0.4)' },
  quizOptionText: { fontFamily: Typography.fontBodyMed, fontSize: Typography.sizeSM, fontWeight: '500', color: Colors.text },
  quizRadio: { width: 20, height: 20, borderRadius: 10, borderWidth: 2, borderColor: '#bfc8c8' },

  clipList: { gap: 12 },
  clipCard: { flexDirection: 'row', alignItems: 'center', gap: 16, backgroundColor: '#f2f4f3', padding: 12, borderRadius: 16, borderWidth: 1, borderColor: 'rgba(191, 200, 200, 0.2)' },
  clipImgBox: { width: 96, height: 64, borderRadius: 12, overflow: 'hidden', backgroundColor: '#e6e9e8' },
  clipPlayOverlay: { position: 'absolute', inset: 0, backgroundColor: 'rgba(0,0,0,0.4)', alignItems: 'center', justifyContent: 'center' },
  clipInfo: { flex: 1, justifyContent: 'center' },
  clipTitle: { fontFamily: Typography.fontBodyMed, fontSize: Typography.sizeSM, fontWeight: '600', color: Colors.text, marginBottom: 4 },
  clipTimestamp: { alignSelf: 'flex-start', backgroundColor: 'rgba(0, 67, 67, 0.1)', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 6 },
  clipTimestampText: { fontFamily: Typography.fontBodyMed, fontSize: 11, fontWeight: '700', color: Colors.secondary },

  quizExplanationBox: { marginTop: 16, padding: 16, backgroundColor: Colors.white, borderRadius: 16, borderWidth: 1, borderColor: 'rgba(191, 200, 200, 0.6)' },
  quizExplanationText: { color: Colors.textMuted, fontSize: 13, fontFamily: Typography.fontBodyMed, lineHeight: 20 },
});
