import { StyleSheet, Platform, StatusBar } from 'react-native';
import { Colors, Typography, Spacing, Radii } from '../../../theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F8FAF9', // Matching the HTML surface color
  },
  header: {
    paddingHorizontal: Spacing.md,
    height: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(248, 250, 249, 0.9)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.04)',
    zIndex: 10,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerTitle: {
    fontFamily: Typography.fontDisplay,
    fontSize: Typography.sizeLG + 2,
    fontWeight: '600',
    color: '#004343',
  },
  badgeNew: {
    backgroundColor: 'rgba(0, 67, 67, 0.1)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: Radii.full,
  },
  badgeNewText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: 12,
    fontWeight: '600',
    color: '#004343',
  },
  markReadBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    height: 36,
    paddingHorizontal: 12,
    borderRadius: Radii.lg,
  },
  markReadText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeXS,
    fontWeight: '600',
    color: '#004343',
  },
  scrollContent: {
    paddingHorizontal: 20, // margin-mobile
    paddingTop: 16,
    paddingBottom: 100, // padding for bottom nav
  },
  filterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.lg,
  },
  filterGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  filterBtnActive: {
    height: 36,
    paddingHorizontal: 16,
    borderRadius: Radii.full,
    backgroundColor: '#004343',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  filterBtnActiveText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: 12,
    fontWeight: '600',
    color: Colors.white,
  },
  filterBtnInactive: {
    height: 36,
    paddingHorizontal: 16,
    borderRadius: Radii.full,
    backgroundColor: Colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  filterBtnInactiveText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: 12,
    fontWeight: '500',
    color: '#3F4948',
  },
  unreadBadge: {
    backgroundColor: 'rgba(254, 137, 62, 0.2)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: Radii.full,
  },
  unreadBadgeText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: 10,
    fontWeight: '700',
    color: '#9b4600',
  },
  section: {
    marginBottom: Spacing.xl,
    gap: 12,
  },
  sectionTitle: {
    fontFamily: Typography.fontBodyMed,
    fontSize: 12,
    fontWeight: '600',
    color: '#3F4948',
    paddingHorizontal: 4,
  },
  card: {
    backgroundColor: Colors.white,
    borderRadius: Radii.xl,
    padding: Spacing.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    overflow: 'hidden',
    position: 'relative',
    gap: 12,
  },
  cardLeftBorder: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: 4,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 8,
    paddingLeft: 4,
  },
  cardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  iconBox: {
    width: 36,
    height: 36,
    borderRadius: Radii.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardTitle: {
    fontFamily: Typography.fontDisplay,
    fontSize: 16,
    fontWeight: '600',
    color: '#202426', // charcoal-text
  },
  cardSubtitle: {
    fontFamily: Typography.fontBodyMed,
    fontSize: 12,
  },
  cardTime: {
    fontFamily: Typography.fontBodyMed,
    fontSize: 12,
    color: '#3F4948',
    flexShrink: 0,
  },
  cardBody: {
    fontFamily: Typography.fontBody,
    fontSize: 16,
    lineHeight: 24,
    color: '#3F4948',
    paddingLeft: 4,
  },
  cardActions: {
    paddingLeft: 4,
    paddingTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  btnPrimary: {
    flex: 1,
    height: 40,
    borderRadius: Radii.md,
    backgroundColor: '#004343',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  btnPrimaryText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: 12,
    fontWeight: '600',
    color: Colors.white,
  },
  btnSecondary: {
    flex: 1,
    height: 40,
    borderRadius: Radii.md,
    backgroundColor: '#eceeed', // surface-container
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  btnSecondaryText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: 12,
    fontWeight: '600',
    color: '#202426',
  },
  
  // Earlier Items
  compactCard: {
    backgroundColor: Colors.white,
    borderRadius: Radii.xl,
    padding: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  compactLeft: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    flex: 1,
  },
  compactContent: {
    flex: 1,
    justifyContent: 'center',
  },
  compactTitle: {
    fontFamily: Typography.fontDisplay,
    fontSize: 15,
    fontWeight: '600',
    color: '#202426',
  },
  compactSubtitle: {
    fontFamily: Typography.fontBody,
    fontSize: 13,
    color: '#3F4948',
  },
  compactTime: {
    fontFamily: Typography.fontBodyMed,
    fontSize: 11,
    color: '#6f7978', // outline
    marginTop: 2,
  },
  btnCompact: {
    height: 36,
    paddingHorizontal: 12,
    borderRadius: Radii.md,
    backgroundColor: '#eceeed',
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnCompactText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: 12,
    fontWeight: '600',
    color: '#202426',
  }
});

