import { StyleSheet, Dimensions } from 'react-native';
import { Colors, Typography, Spacing, Radii } from '../../theme';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
const CARD_WIDTH = SCREEN_WIDTH - Spacing.md * 2;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: Colors.dominant,
    overflow: 'hidden',
  },
  scrollContent: {
    paddingBottom: Spacing.xl,
  },
  stickyHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    width: '100%',
    zIndex: 10,
    backgroundColor: Colors.dominant,
  },

  // ── 0. User Header ────────────────────────────────────────────────────────
  userHeaderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.md,
    paddingTop: Spacing.md,
    paddingBottom: Spacing.xs,
  },
  userInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  avatarCircle: {
    width: 38,
    height: 38,
    borderRadius: Radii.full,
    backgroundColor: Colors.secondary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeSM,
    color: Colors.white,
    fontWeight: '700',
  },
  userGreeting: {
    fontFamily: Typography.fontDisplay,
    fontSize: Typography.sizeMD,
    color: Colors.text,
    fontWeight: '700',
  },
  userSubgreeting: {
    fontFamily: Typography.fontBody,
    fontSize: Typography.sizeXS,
    color: Colors.textMuted,
  },
  notificationButton: {
    width: 38,
    height: 38,
    borderRadius: Radii.full,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.secondarySubtle,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // ── 1. Search Section ─────────────────────────────────────────────────────
  searchBarSection: {
    paddingHorizontal: Spacing.md,
    paddingTop: Spacing.sm,
    paddingBottom: 0,
  },
  pillsAndFilterSection: {
    paddingTop: 0,
  },
  searchContainer: {
    flexDirection: 'row',
    marginBottom: 2,
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: Radii.full,
    borderWidth: 1,
    borderColor: Colors.secondarySubtle,
    paddingHorizontal: Spacing.md,
    height: 56,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  searchIcon: {
    marginRight: Spacing.sm,
  },
  searchInput: {
    flex: 1,
    fontFamily: Typography.fontBody,
    fontSize: Typography.sizeLG,
    color: Colors.text,
    paddingVertical: 0,
  },
  micButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.secondary,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: Spacing.xs,
  },
  quickFiltersContainer: {
    paddingTop: Spacing.sm,
    paddingBottom: Spacing.sm,
    paddingHorizontal: Spacing.md,
    gap: 8,
  },
  quickFilterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.secondarySubtle,
    borderRadius: Radii.full,
    paddingHorizontal: 14,
    paddingVertical: 8,
    gap: 6,
  },
  quickFilterChipActive: {
    backgroundColor: Colors.secondary,
    borderColor: Colors.secondary,
  },
  quickFilterText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeMD,
    color: Colors.textMuted,
  },
  quickFilterTextActive: {
    color: Colors.white,
    fontWeight: '600',
  },

  // ── 2. Filter Bar & Tabs ──────────────────────────────────────────────────
  filterBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: '#E1E3E2',
    paddingBottom: Spacing.xs,
  },
  tabsContainer: {
    flexGrow: 1,
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.lg,
  },
  tabButton: {
    paddingVertical: Spacing.xs,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabButtonActive: {
    borderBottomColor: Colors.secondary,
  },
  tabText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeMD,
    color: Colors.textMuted,
  },
  tabTextActive: {
    color: Colors.secondary,
    fontWeight: '600',
  },
  tuneButton: {
    width: 34,
    height: 34,
    borderRadius: Radii.full,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.secondarySubtle,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // ── Feed Container & Cards ────────────────────────────────────────────────\n\n  // ── Feed Container & Cards ────────────────────────────────────────────────
  emptyState: {
    padding: Spacing.xl,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: Spacing.xxl,
  },
  emptyStateText: {
    fontFamily: Typography.fontDisplay,
    fontSize: Typography.sizeLG,
    fontWeight: '600',
    color: Colors.text,
    marginTop: Spacing.md,
  },
  emptyStateSubtext: {
    fontFamily: Typography.fontBody,
    fontSize: Typography.sizeSM,
    color: Colors.textMuted,
    marginTop: Spacing.xs,
  },
  feedContainer: {
    paddingHorizontal: Spacing.md,
    gap: Spacing.lg,
  },
  card: {
    backgroundColor: Colors.white,
    borderRadius: Radii.xl,
    borderWidth: 1,
    borderColor: Colors.secondarySubtle,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
    marginBottom: Spacing.lg,
    marginHorizontal: Spacing.md,
  },

  // Card Header
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: Spacing.md,
  },
  authorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
    marginRight: 8,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.surface,
  },
  authorName: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeMD,
    fontWeight: '600',
    color: Colors.text,
  },
  timeAgo: {
    fontFamily: Typography.fontBody,
    fontSize: Typography.sizeSM,
    color: Colors.textMuted,
    marginTop: 2,
  },
  authorInitialBubble: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(15, 92, 92, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  authorInitialText: {
    fontFamily: Typography.fontDisplay,
    fontSize: Typography.sizeMD,
    fontWeight: '700',
    color: '#0f5c5c',
  },
  audioBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(254, 137, 62, 0.12)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: Radii.sm,
  },
  audioBadgeText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: 11,
    fontWeight: '700',
    color: Colors.accent,
    textTransform: 'uppercase',
  },
  audioTopic: {
    fontFamily: Typography.fontDisplay,
    fontSize: Typography.sizeMD,
    fontWeight: '600',
    color: Colors.text,
    paddingHorizontal: Spacing.md,
    marginBottom: Spacing.sm,
  },
  audioStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0f5c5c',
    marginHorizontal: Spacing.md,
    marginBottom: Spacing.md,
    padding: Spacing.sm,
    borderRadius: Radii.lg,
    gap: 12,
  },
  audioPlayBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  waveformRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    height: 40,
  },
  waveBar: {
    width: 4,
    backgroundColor: Colors.white,
    borderRadius: 2,
  },
  audioDurationText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeXS,
    color: Colors.white,
  },

  // Card Actions
  cardActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm + 2,
    borderTopWidth: 1,
    borderTopColor: '#F2F4F3',
  },
  leftActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  actionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  actionText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeSM,
    color: Colors.textMuted,
  },
  cardFooterNote: {
    paddingHorizontal: Spacing.md,
    paddingBottom: Spacing.md,
  },
  savedNoteText: {
    fontFamily: Typography.fontBody,
    fontSize: Typography.sizeXS,
    color: Colors.textMuted,
  },

  // Post 1: Video Card specific
  videoHeroContainer: {
    height: 340,
    width: '100%',
    position: 'relative',
    justifyContent: 'space-between',
    backgroundColor: '#0a1010',
  },
  muteButton: {
    position: 'absolute',
    bottom: Spacing.md,
    right: Spacing.md,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 20,
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  videoThumbnail: {
    ...StyleSheet.absoluteFillObject,
  },
  videoOverlayGradient: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(10, 61, 61, 0.45)',
  },
  videoBadgesRow: {
    flexDirection: 'row',
    gap: 8,
    padding: Spacing.md,
  },
  glassBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: Radii.full,
    gap: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  glassBadgeText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeXS,
    color: Colors.white,
  },
  playButtonWrapper: {
    alignSelf: 'center',
  },
  playCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoBottomOverlay: {
    padding: Spacing.md,
  },
  videoTitle: {
    fontFamily: Typography.fontDisplay,
    fontSize: Typography.sizeXL,
    fontWeight: '700',
    color: Colors.white,
    marginBottom: 4,
  },
  videoSubtitle: {
    fontFamily: Typography.fontBody,
    fontSize: Typography.sizeSM,
    color: 'rgba(255, 255, 255, 0.9)',
    lineHeight: 20,
  },


  actionCount: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeSM,
    color: Colors.textMuted,
  },

  // Blog Card
  blogHeroImage: {
    width: '100%',
    height: 180,
  },
  blogBody: {
    padding: Spacing.md,
  },
  blogTitle: {
    fontFamily: Typography.fontDisplay,
    fontSize: Typography.sizeXL,
    fontWeight: '700',
    color: Colors.text,
    marginBottom: 6,
  },
  blogExcerpt: {
    fontFamily: Typography.fontBody,
    fontSize: Typography.sizeMD,
    color: Colors.textMuted,
    lineHeight: 22,
    marginBottom: 12,
  },
  readMoreBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  readMoreText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeMD,
    color: Colors.secondary,
    fontWeight: '600',
  },

  // Post 2: Story Card specific
  storyContent: {
    paddingHorizontal: Spacing.md,
    paddingBottom: Spacing.sm,
  },
  editorialTag: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(254, 137, 62, 0.18)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: Radii.sm,
    marginBottom: Spacing.xs,
  },
  editorialTagText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: 10,
    fontWeight: '700',
    color: Colors.accent,
    letterSpacing: 0.8,
  },
  storyTitle: {
    fontFamily: Typography.fontDisplay,
    fontSize: Typography.sizeXL,
    fontWeight: '600',
    color: Colors.text,
    marginBottom: 6,
  },
  storyParagraph: {
    fontFamily: Typography.fontBody,
    fontSize: Typography.sizeSM,
    color: Colors.textMuted,
    lineHeight: 22,
  },
  storyImage: {
    height: 200,
    width: '100%',
  },
  storyButtonContainer: {
    padding: Spacing.md,
  },
  readStoryButton: {
    width: '100%',
    paddingVertical: 12,
    backgroundColor: Colors.surface,
    borderRadius: Radii.lg,
    alignItems: 'center',
  },
  readStoryButtonText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeSM,
    color: Colors.secondary,
    fontWeight: '600',
  },

  // ── Cultural Thread Section ───────────────────────────────────────────────
  threadSectionWrapper: {
    position: 'relative',
    marginVertical: Spacing.xs,
  },
  threadLine: {
    position: 'absolute',
    left: 12,
    top: 0,
    bottom: 0,
    width: 2,
    backgroundColor: Colors.secondarySubtle,
    borderRadius: 1,
  },
  threadContent: {
    gap: Spacing.md,
    paddingLeft: Spacing.lg,
  },

  // Post 3: Knowledge Keeper Card
  knowledgeCard: {
    backgroundColor: Colors.secondary,
    borderRadius: Radii.xl,
    padding: Spacing.md,
    position: 'relative',
    overflow: 'hidden',
    elevation: 3,
  },
  knowledgeGlowTop: {
    position: 'absolute',
    top: -40,
    right: -40,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(15, 92, 92, 0.4)',
  },
  knowledgeGlowBottom: {
    position: 'absolute',
    bottom: -30,
    left: -30,
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: Colors.accentSubtle,
  },
  knowledgeCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.sm,
  },
  knowledgeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  knowledgeBadgeText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: 11,
    color: '#ACEEEE',
    letterSpacing: 0.8,
    fontWeight: '600',
  },
  knowledgeProfileRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
    marginBottom: Spacing.sm,
  },
  knowledgeAvatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: '#ACEEEE',
  },
  knowledgeInfo: {
    flex: 1,
  },
  knowledgeName: {
    fontFamily: Typography.fontDisplay,
    fontSize: Typography.sizeLG,
    fontWeight: '700',
    color: Colors.white,
    marginBottom: 2,
  },
  knowledgeTitle: {
    fontFamily: Typography.fontBody,
    fontSize: Typography.sizeXS,
    color: '#ACEEEE',
    marginBottom: 6,
  },
  knowledgeTag: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: Radii.sm,
    borderWidth: 1,
    borderColor: 'rgba(172, 238, 238, 0.25)',
  },
  knowledgeTagText: {
    fontFamily: Typography.fontBody,
    fontSize: 10,
    color: '#ACEEEE',
  },
  knowledgeQuote: {
    fontFamily: Typography.fontDisplay,
    fontSize: Typography.sizeMD,
    fontStyle: 'italic',
    color: 'rgba(255, 255, 255, 0.95)',
    borderLeftWidth: 3,
    borderLeftColor: Colors.accent,
    paddingLeft: Spacing.sm,
    marginVertical: Spacing.xs,
    lineHeight: 22,
  },
  knowledgeFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.15)',
    paddingTop: Spacing.sm,
    marginTop: Spacing.sm,
  },
  knowledgeActionText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeXS,
    color: '#ACEEEE',
  },
  knowledgeSavedText: {
    fontFamily: Typography.fontBody,
    fontSize: 11,
    color: '#ACEEEE',
  },

  // Post 4: Cultural Discovery Card (Word of the Day)
  wordCard: {
    backgroundColor: Colors.white,
    borderRadius: Radii.lg,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.secondarySubtle,
  },
  wordCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.xs,
  },
  wordTagText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: 11,
    fontWeight: '700',
    color: Colors.textMuted,
    letterSpacing: 1,
  },
  wordBodyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginVertical: Spacing.xs,
  },
  wordMainContainer: {
    flex: 1,
  },
  sinhalaWord: {
    fontSize: 26,
    fontWeight: '700',
    color: Colors.secondary,
  },
  transliteration: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeXS,
    color: Colors.textMuted,
    marginTop: 2,
  },
  wordArrow: {
    marginHorizontal: 2,
  },
  definitionBox: {
    flex: 1.4,
    backgroundColor: '#F2F4F3',
    padding: Spacing.sm,
    borderRadius: Radii.md,
    borderWidth: 1,
    borderColor: '#E1E3E2',
  },
  definitionText: {
    fontFamily: Typography.fontBody,
    fontSize: Typography.sizeXS,
    color: Colors.text,
    lineHeight: 18,
  },
  wordFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: '#F2F4F3',
    paddingTop: Spacing.sm,
    marginTop: Spacing.xs,
  },

  // Post 5: Multi-Image Carousel Card
  carouselTextContainer: {
    paddingHorizontal: Spacing.md,
    marginBottom: Spacing.sm,
  },
  carouselSubtitle: {
    fontFamily: Typography.fontBody,
    fontSize: Typography.sizeSM,
    color: Colors.textMuted,
    marginTop: 4,
  },
  carouselSlide: {
    width: CARD_WIDTH,
    height: CARD_WIDTH,
    position: 'relative',
  },
  carouselImage: {
    width: '100%',
    height: '100%',
  },
  carouselBadge: {
    position: 'absolute',
    bottom: 14,
    left: 14,
    backgroundColor: 'rgba(248, 250, 249, 0.92)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: Radii.md,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.4)',
  },
  carouselBadgeText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeSM,
    color: Colors.secondary,
    fontWeight: '600',
  },
  paginationDots: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.surface,
  },
  dotActive: {
    backgroundColor: Colors.secondary,
  },

  // Post 6: Regional Discovery Module
  spotlightCard: {
    backgroundColor: 'rgba(254, 137, 62, 0.08)',
    borderRadius: Radii.xl,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: 'rgba(254, 137, 62, 0.25)',
  },
  spotlightHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.md,
  },
  spotlightTagText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: 11,
    fontWeight: '700',
    color: Colors.accent,
    letterSpacing: 1,
    marginBottom: 2,
  },
  spotlightTitle: {
    fontFamily: Typography.fontDisplay,
    fontSize: Typography.sizeXL,
    fontWeight: '700',
    color: Colors.text,
  },
  mapIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  spotlightScrollContainer: {
    gap: 12,
    paddingBottom: Spacing.xs,
  },
  spotlightItemCard: {
    width: 130,
    height: 170,
    borderRadius: Radii.lg,
    overflow: 'hidden',
    position: 'relative',
  },
  spotlightItemImage: {
    width: '100%',
    height: '100%',
  },
  spotlightOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
  },
  spotlightItemContent: {
    position: 'absolute',
    bottom: 10,
    left: 10,
    right: 10,
  },
  spotlightItemTitle: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeSM,
    fontWeight: '700',
    color: Colors.white,
  },
  spotlightItemSub: {
    fontFamily: Typography.fontBody,
    fontSize: Typography.sizeXS,
    color: 'rgba(255, 255, 255, 0.85)',
  },
  exploreRegionBtn: {
    marginTop: Spacing.md,
    width: '100%',
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: Colors.accent,
    borderRadius: Radii.lg,
    alignItems: 'center',
  },
  exploreRegionBtnText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeSM,
    color: Colors.accent,
    fontWeight: '600',
  },
  bottomSpacer: {
    height: Spacing.xl,
  },

  // ── Voice Search Modal ────────────────────────────────────────────────────
  voiceModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  voiceModalContent: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: Spacing.xl,
    paddingBottom: 36,
  },
  voiceModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: Spacing.lg,
  },
  voiceCloseButton: {
    marginLeft: 'auto',
    padding: 6,
  },
  voiceMicCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#0f5c5c',
    alignItems: 'center',
    justifyContent: 'center',
  },
  voiceModalTitle: {
    fontFamily: Typography.fontDisplay,
    fontSize: Typography.sizeLG,
    fontWeight: '700',
    color: Colors.text,
  },
  voiceSearchInput: {
    width: '100%',
    borderWidth: 1.5,
    borderColor: '#0f5c5c',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeMD,
    color: Colors.text,
    backgroundColor: '#f5fafa',
    marginBottom: Spacing.lg,
  },
  voiceSuggestLabel: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeXS,
    color: Colors.textMuted,
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  voiceSuggestRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: Spacing.xl,
  },
  voiceSuggestChip: {
    backgroundColor: 'rgba(15, 92, 92, 0.08)',
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: 'rgba(15, 92, 92, 0.15)',
  },
  voiceSuggestChipText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeSM,
    color: '#0f5c5c',
    fontWeight: '600',
  },
  voiceSearchBtn: {
    backgroundColor: '#0f5c5c',
    borderRadius: 14,
    paddingVertical: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  voiceSearchBtnText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeMD,
    fontWeight: '700',
    color: Colors.white,
  },
  followButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#fe893e',
    borderWidth: 1,
    borderColor: '#fe893e',
  },
  followingButton: {
    backgroundColor: 'rgba(254, 137, 62, 0.15)',
    borderColor: 'rgba(254, 137, 62, 0.3)',
  },
  followButtonText: {
    fontFamily: Typography.fontBodyMed,
    fontSize: Typography.sizeSM,
    color: '#ffffff',
    fontWeight: '700',
  },
  followingButtonText: {
    color: '#fe893e',
  },
  loaderContainer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#0a1010',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
    zIndex: 5,
  },
  loaderGrid: {
    width: 45,
    height: 45,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignContent: 'space-between',
  },
  loaderSquare: {
    width: 20,
    height: 20,
    borderWidth: 2,
    borderColor: '#fe893e',
    backgroundColor: 'transparent',
  },
});
