import type { AppLocale } from '../store/localeStore';

/**
 * UI copy for the elder "Hire a Creator" flow (post a request, My Requests,
 * applicant review, creator conversation) in the three onboarding languages.
 *
 * English is the source of truth — every other locale must define exactly
 * the same keys (enforced by the `HireStrings` type). `{name}` tokens are
 * interpolated by `useHireStrings().t`; keys ending `_one`/`_other` are
 * picked by plural category via `t(key, { count })`.
 *
 * NOTE: Sinhala and Tamil copy is a first draft — have a native speaker
 * review tone/register (especially for elder-facing wording) before release.
 */
const en = {
  // ── Shared ────────────────────────────────────────────────────────────────
  'common.back': 'Go back',
  'common.retry': 'Try again',
  'common.loading': 'Loading',
  'common.openMenu': 'Open menu',
  'common.notifications': 'Notifications',
  'common.voiceInput': 'Voice input for {field}',
  'common.stopVoiceInput': 'Stop voice input for {field}',
  'common.listening': 'Listening…',
  'common.micPermission': 'Microphone access is needed for voice typing.',
  'common.micError': "Couldn't hear that — please try again.",

  // ── Screen 8 — Post a request ─────────────────────────────────────────────
  'post.headerTitle': 'Hire a Creator',
  'post.heading': 'Request Creator Assistance',
  'post.intro': 'To get help from a creator, provide the following details:',
  'post.guidance.1': "A short description of what you'd like recorded",
  'post.guidance.2': 'Whether you want it as audio, video, or an article',
  'post.guidance.3': "Roughly how soon you'd like it done",
  'post.guidance.4': 'Any specific words or topics that are important to include',
  'post.guidance.5': 'Anything a creator should know to prepare',
  'post.guidance.6': 'Anything that would help a creator find you or understand your story',
  'post.titleLabel': 'Title of the request',
  'post.titlePlaceholder': 'Fishing stories from my childhood',
  'post.descriptionLabel': 'Details',
  'post.descriptionPlaceholder': 'I want to talk about how we celebrated New Year in my village',
  'post.submit': 'Send for Review',
  'post.submitting': 'Sending…',
  'post.reassurance': "Our team will review this before it's shared with creators.",
  'post.error.titleRequired': 'Please give your request a short title.',
  'post.error.descriptionRequired': "Please tell us what you'd like help with.",
  'post.error.submitFailed': "We couldn't send your request. Please try again.",
  'post.field.title': 'the request title',
  'post.field.description': 'the details',

  // ── Screen 9 — My Requests ────────────────────────────────────────────────
  'requests.headerTitle': 'My Requests',
  'requests.heading': 'My Requests',
  'requests.postedNotice': "Your request was sent. We'll review it and let you know when it's live.",
  'requests.postedNoticeDismiss': 'Dismiss',
  'requests.status.PENDING_REVIEW': 'Pending Review',
  'requests.status.OPEN': 'Open',
  'requests.status.REVIEWING': 'Reviewing Applicants',
  'requests.status.ASSIGNED': 'Creator Assigned',
  'requests.status.COMPLETED': 'Completed',
  'requests.status.NOT_APPROVED': 'Not approved',
  'requests.posted': 'Posted {date}',
  'requests.viewApplicants': 'View Applicants ({count})',
  'requests.message': 'Message',
  'requests.messageAccessibility': 'Message {name}',
  'requests.assignedCreator': 'Your creator',
  'requests.creatorFallback': 'Your creator',
  'requests.statusAccessibility': 'Status: {status}',
  'requests.empty.title': "You haven't asked for help yet",
  'requests.empty.body': 'Tell us what story you want to preserve and a young creator can help.',
  'requests.empty.cta': 'Ask for help',
  'requests.newRequest': 'New request',
  'requests.loadError.title': "Couldn't load your requests",
  'requests.loadError.body': 'Check your connection and try again.',

  // ── Screen 10 — Applicant review ──────────────────────────────────────────
  'applicants.headerTitle': 'Applicants',
  'applicants.heading': 'Replies for Your Request',
  'applicants.forJob': 'For: {title}',
  'applicants.appliedTo': 'Applied to: {title}',
  'applicants.empty': "No creators have applied yet. We'll let you know when they do.",
  'applicants.allResponded': "You've replied to everyone so far. New applicants will show up here.",
  'applicants.loadError': "Couldn't load the applicants. Please try again.",
  'applicants.rating': 'Rated {rating} out of 5',
  'applicants.noRating': 'New creator — no ratings yet',
  'applicants.messageLabel': 'Message:',
  'applicants.noMessage': "This creator didn't leave a message.",
  'applicants.replyVoice': 'Reply with voice',
  'applicants.replyVoiceAccessibility': 'Record a voice reply to {name}',
  'applicants.voiceReplySaved': 'Voice reply saved on this device',
  'applicants.approve': 'Approve',
  'applicants.approving': 'Approving…',
  'applicants.approveAccessibility': 'Approve {name} for this request',
  'applicants.reject': 'Reject',
  'applicants.rejectAccessibility': 'Reject {name} for this request',
  'applicants.notSelected': 'Not selected',
  'applicants.selected': 'Chosen',
  'applicants.actionError': "That didn't go through. Please try again.",
  'applicants.messageFrom': 'Message from {name}',

  // ── Voice-reply sheet ─────────────────────────────────────────────────────
  'voice.title': 'Reply with your voice',
  'voice.hint': 'Tap the microphone and speak. You can ask a question or say something back before you decide.',
  'voice.start': 'Start recording',
  'voice.stop': 'Stop recording',
  'voice.recording': 'Recording…',
  'voice.recorded': 'Recorded {duration}',
  'voice.recordAgain': 'Record again',
  'voice.save': 'Save reply',
  'voice.close': 'Close',

  // ── Reject-reason sheet ───────────────────────────────────────────────────
  'reject.title': 'Let them know why? (optional)',
  'reject.reassurance': "Skipping is completely fine — you don't have to explain.",
  'reject.placeholder': 'A short, kind note…',
  'reject.field': 'a note to the creator',
  'reject.skip': 'Skip',
  'reject.send': 'Send',
  'reject.sending': 'Sending…',
  'reject.close': 'Close',

  // ── Creator conversation ──────────────────────────────────────────────────
  'chat.headerTitle': 'Messages',
  'chat.about': 'About: {title}',
  'chat.intro': 'You chose {name}. Say hello and plan your recording together.',
  'chat.replyPlaceholder': 'Type or speak your reply',
  'chat.replyLabel': 'Your reply',
  'chat.send': 'Send reply',
  'chat.you': 'You',
} as const;

export type HireStringKey = keyof typeof en;
export type HireStrings = Record<HireStringKey, string>;

const si: HireStrings = {
  'common.back': 'ආපසු යන්න',
  'common.retry': 'නැවත උත්සාහ කරන්න',
  'common.loading': 'පූරණය වෙමින්',
  'common.openMenu': 'මෙනුව විවෘත කරන්න',
  'common.notifications': 'දැනුම්දීම්',
  'common.voiceInput': '{field} සඳහා හඬ ආදානය',
  'common.stopVoiceInput': '{field} සඳහා හඬ ආදානය නවත්වන්න',
  'common.listening': 'සවන් දෙමින්…',
  'common.micPermission': 'හඬ ටයිප් කිරීමට මයික්‍රෝෆෝනයට ප්‍රවේශය අවශ්‍යයි.',
  'common.micError': 'එය ඇසුණේ නැත — කරුණාකර නැවත උත්සාහ කරන්න.',

  'post.headerTitle': 'නිර්මාණකරුවෙකු ඉල්ලන්න',
  'post.heading': 'නිර්මාණකරුවෙකුගේ සහාය ඉල්ලන්න',
  'post.intro': 'නිර්මාණකරුවෙකුගේ උදව් ලබා ගැනීමට පහත විස්තර සපයන්න:',
  'post.guidance.1': 'ඔබ පටිගත කිරීමට කැමති දේ පිළිබඳ කෙටි විස්තරයක්',
  'post.guidance.2': 'ඔබට ඒ ශ්‍රව්‍ය, වීඩියෝ හෝ ලිපියක් ලෙස අවශ්‍යද යන වග',
  'post.guidance.3': 'එය ඉවර කර ගැනීමට ඔබට අවශ්‍ය ආසන්න කාලය',
  'post.guidance.4': 'ඇතුළත් කිරීමට වැදගත් විශේෂ වචන හෝ මාතෘකා',
  'post.guidance.5': 'සූදානම් වීමට නිර්මාණකරුවෙකු දැනගත යුතු ඕනෑම දෙයක්',
  'post.guidance.6': 'නිර්මාණකරුවෙකුට ඔබව සොයා ගැනීමට හෝ ඔබේ කතාව තේරුම් ගැනීමට උපකාරී වන ඕනෑම දෙයක්',
  'post.titleLabel': 'ඉල්ලීමේ මාතෘකාව',
  'post.titlePlaceholder': 'මගේ ළමා කාලයේ ධීවර කතා',
  'post.descriptionLabel': 'විස්තර',
  'post.descriptionPlaceholder': 'අපේ ගමේ අලුත් අවුරුද්ද සැමරූ ආකාරය ගැන කතා කරන්න මට ඕනේ',
  'post.submit': 'සමාලෝචනයට යවන්න',
  'post.submitting': 'යවමින්…',
  'post.reassurance': 'නිර්මාණකරුවන් වෙත බෙදා හැරීමට පෙර අපගේ කණ්ඩායම මෙය පරීක්ෂා කරනු ඇත.',
  'post.error.titleRequired': 'කරුණාකර ඔබේ ඉල්ලීමට කෙටි මාතෘකාවක් දෙන්න.',
  'post.error.descriptionRequired': 'ඔබට අවශ්‍ය උදව් කුමක්දැයි අපට කියන්න.',
  'post.error.submitFailed': 'ඔබේ ඉල්ලීම යැවීමට නොහැකි විය. කරුණාකර නැවත උත්සාහ කරන්න.',
  'post.field.title': 'ඉල්ලීමේ මාතෘකාව',
  'post.field.description': 'විස්තර',

  'requests.headerTitle': 'මගේ ඉල්ලීම්',
  'requests.heading': 'මගේ ඉල්ලීම්',
  'requests.postedNotice': 'ඔබේ ඉල්ලීම යවන ලදී. අපි එය පරීක්ෂා කර ප්‍රකාශයට පත් වූ විට ඔබට දන්වන්නෙමු.',
  'requests.postedNoticeDismiss': 'වසන්න',
  'requests.status.PENDING_REVIEW': 'සමාලෝචනය බලාපොරොත්තුවෙන්',
  'requests.status.OPEN': 'විවෘතයි',
  'requests.status.REVIEWING': 'අයදුම්කරුවන් සමාලෝචනය',
  'requests.status.ASSIGNED': 'නිර්මාණකරු පත් කර ඇත',
  'requests.status.COMPLETED': 'සම්පූර්ණයි',
  'requests.status.NOT_APPROVED': 'අනුමත නොවීය',
  'requests.posted': '{date} දින යවන ලදී',
  'requests.viewApplicants': 'අයදුම්කරුවන් බලන්න ({count})',
  'requests.message': 'පණිවිඩය',
  'requests.messageAccessibility': '{name} වෙත පණිවිඩයක් යවන්න',
  'requests.assignedCreator': 'ඔබේ නිර්මාණකරු',
  'requests.creatorFallback': 'ඔබේ නිර්මාණකරු',
  'requests.statusAccessibility': 'තත්ත්වය: {status}',
  'requests.empty.title': 'ඔබ තවම උදව් ඉල්ලා නැත',
  'requests.empty.body': 'ආරක්ෂා කිරීමට කැමති කතාව අපට කියන්න, තරුණ නිර්මාණකරුවෙකුට උදව් කළ හැක.',
  'requests.empty.cta': 'උදව් ඉල්ලන්න',
  'requests.newRequest': 'නව ඉල්ලීමක්',
  'requests.loadError.title': 'ඔබේ ඉල්ලීම් පූරණය කළ නොහැකි විය',
  'requests.loadError.body': 'ඔබේ සම්බන්ධතාව පරීක්ෂා කර නැවත උත්සාහ කරන්න.',

  'applicants.headerTitle': 'අයදුම්කරුවන්',
  'applicants.heading': 'ඔබේ ඉල්ලීමට පිළිතුරු',
  'applicants.forJob': 'සඳහා: {title}',
  'applicants.appliedTo': 'අයදුම් කළ ඉල්ලීම: {title}',
  'applicants.empty': 'තවම කිසිවෙක් අයදුම් කර නැත. අයදුම් කළ විට අපි ඔබට දන්වන්නෙමු.',
  'applicants.allResponded': 'ඔබ මෙතෙක් සියලු දෙනාට පිළිතුරු දී ඇත. අලුත් අයදුම්කරුවන් මෙහි පෙන්වයි.',
  'applicants.loadError': 'අයදුම්කරුවන් පූරණය කළ නොහැකි විය. කරුණාකර නැවත උත්සාහ කරන්න.',
  'applicants.rating': 'තරු {rating} / 5 ක ශ්‍රේණිගතයි',
  'applicants.noRating': 'අලුත් නිර්මාණකරුවෙක් — තවම ශ්‍රේණිගත කර නැත',
  'applicants.messageLabel': 'පණිවිඩය:',
  'applicants.noMessage': 'මෙම නිර්මාණකරු පණිවිඩයක් තබා නැත.',
  'applicants.replyVoice': 'හඬින් පිළිතුරු දෙන්න',
  'applicants.replyVoiceAccessibility': '{name} වෙත හඬ පිළිතුරක් පටිගත කරන්න',
  'applicants.voiceReplySaved': 'හඬ පිළිතුර මෙම උපාංගයේ සුරකින ලදී',
  'applicants.approve': 'අනුමත කරන්න',
  'applicants.approving': 'අනුමත කරමින්…',
  'applicants.approveAccessibility': 'මෙම ඉල්ලීම සඳහා {name} අනුමත කරන්න',
  'applicants.reject': 'ප්‍රතික්ෂේප කරන්න',
  'applicants.rejectAccessibility': 'මෙම ඉල්ලීම සඳහා {name} ප්‍රතික්ෂේප කරන්න',
  'applicants.notSelected': 'තෝරාගත්තේ නැත',
  'applicants.selected': 'තෝරාගත්',
  'applicants.actionError': 'එය සම්පූර්ණ නොවීය. කරුණාකර නැවත උත්සාහ කරන්න.',
  'applicants.messageFrom': '{name} ගෙන් පණිවිඩය',

  'voice.title': 'ඔබේ හඬින් පිළිතුරු දෙන්න',
  'voice.hint': 'මයික්‍රෝෆෝනය ඔබා කතා කරන්න. තීරණය කිරීමට පෙර ප්‍රශ්නයක් අසන්න හෝ යමක් කියන්න.',
  'voice.start': 'පටිගත කිරීම ආරම්භ කරන්න',
  'voice.stop': 'පටිගත කිරීම නවත්වන්න',
  'voice.recording': 'පටිගත කරමින්…',
  'voice.recorded': 'පටිගත කළා {duration}',
  'voice.recordAgain': 'නැවත පටිගත කරන්න',
  'voice.save': 'පිළිතුර සුරකින්න',
  'voice.close': 'වසන්න',

  'reject.title': 'හේතුව දන්වන්නද? (අවශ්‍ය නොවේ)',
  'reject.reassurance': 'මඟ හැරීම සම්පූර්ණයෙන්ම හරි — ඔබට පැහැදිලි කිරීමට අවශ්‍ය නැත.',
  'reject.placeholder': 'කෙටි, කරුණාවන්ත සටහනක්…',
  'reject.field': 'නිර්මාණකරුට සටහනක්',
  'reject.skip': 'මඟ හරින්න',
  'reject.send': 'යවන්න',
  'reject.sending': 'යවමින්…',
  'reject.close': 'වසන්න',

  'chat.headerTitle': 'පණිවිඩ',
  'chat.about': 'ගැන: {title}',
  'chat.intro': 'ඔබ {name} තෝරා ගත්තා. ආචාර කර ඔබේ පටිගත කිරීම එකට සැලසුම් කරන්න.',
  'chat.replyPlaceholder': 'ඔබේ පිළිතුර ටයිප් කරන්න හෝ කියන්න',
  'chat.replyLabel': 'ඔබේ පිළිතුර',
  'chat.send': 'පිළිතුර යවන්න',
  'chat.you': 'ඔබ',
};

const ta: HireStrings = {
  'common.back': 'பின்செல்',
  'common.retry': 'மீண்டும் முயலவும்',
  'common.loading': 'ஏற்றுகிறது',
  'common.openMenu': 'பட்டியலைத் திற',
  'common.notifications': 'அறிவிப்புகள்',
  'common.voiceInput': '{field}க்கான குரல் உள்ளீடு',
  'common.stopVoiceInput': '{field}க்கான குரல் உள்ளீட்டை நிறுத்து',
  'common.listening': 'கேட்கிறது…',
  'common.micPermission': 'குரல் தட்டச்சுக்கு மைக்ரோஃபோன் அணுகல் தேவை.',
  'common.micError': 'அது கேட்கவில்லை — மீண்டும் முயலவும்.',

  'post.headerTitle': 'படைப்பாளரை அழைக்கவும்',
  'post.heading': 'படைப்பாளரின் உதவியைக் கேளுங்கள்',
  'post.intro': 'ஒரு படைப்பாளரின் உதவியைப் பெற, பின்வரும் விவரங்களை வழங்கவும்:',
  'post.guidance.1': 'நீங்கள் பதிவு செய்ய விரும்புவதைப் பற்றிய ஒரு சிறு விளக்கம்',
  'post.guidance.2': 'ஒலி, காணொளி அல்லது கட்டுரை — எது வேண்டும் என்பது',
  'post.guidance.3': 'எவ்வளவு விரைவில் முடிக்க வேண்டும் என்பது',
  'post.guidance.4': 'சேர்க்க வேண்டிய முக்கியமான சொற்கள் அல்லது தலைப்புகள்',
  'post.guidance.5': 'தயாராக படைப்பாளர் தெரிந்துகொள்ள வேண்டிய எதுவும்',
  'post.guidance.6': 'படைப்பாளர் உங்களைக் கண்டறிய அல்லது உங்கள் கதையைப் புரிந்துகொள்ள உதவும் எதுவும்',
  'post.titleLabel': 'கோரிக்கையின் தலைப்பு',
  'post.titlePlaceholder': 'என் சிறுவயது மீன்பிடிக் கதைகள்',
  'post.descriptionLabel': 'விவரங்கள்',
  'post.descriptionPlaceholder': 'எங்கள் கிராமத்தில் புத்தாண்டை எப்படிக் கொண்டாடினோம் என்பதைப் பற்றிப் பேச விரும்புகிறேன்',
  'post.submit': 'மதிப்பாய்வுக்கு அனுப்பு',
  'post.submitting': 'அனுப்புகிறது…',
  'post.reassurance': 'படைப்பாளர்களுடன் பகிர்வதற்கு முன் எங்கள் குழு இதை மதிப்பாய்வு செய்யும்.',
  'post.error.titleRequired': 'உங்கள் கோரிக்கைக்கு ஒரு சிறு தலைப்பைக் கொடுங்கள்.',
  'post.error.descriptionRequired': 'உங்களுக்கு என்ன உதவி வேண்டும் என்று சொல்லுங்கள்.',
  'post.error.submitFailed': 'உங்கள் கோரிக்கையை அனுப்ப முடியவில்லை. மீண்டும் முயலவும்.',
  'post.field.title': 'கோரிக்கையின் தலைப்பு',
  'post.field.description': 'விவரங்கள்',

  'requests.headerTitle': 'என் கோரிக்கைகள்',
  'requests.heading': 'என் கோரிக்கைகள்',
  'requests.postedNotice': 'உங்கள் கோரிக்கை அனுப்பப்பட்டது. அதைச் சரிபார்த்து, வெளியானதும் தெரிவிப்போம்.',
  'requests.postedNoticeDismiss': 'மூடு',
  'requests.status.PENDING_REVIEW': 'மதிப்பாய்வுக்காகக் காத்திருக்கிறது',
  'requests.status.OPEN': 'திறந்துள்ளது',
  'requests.status.REVIEWING': 'விண்ணப்பங்கள் பரிசீலனையில்',
  'requests.status.ASSIGNED': 'படைப்பாளர் நியமிக்கப்பட்டார்',
  'requests.status.COMPLETED': 'நிறைவடைந்தது',
  'requests.status.NOT_APPROVED': 'அங்கீகரிக்கப்படவில்லை',
  'requests.posted': '{date} அன்று அனுப்பப்பட்டது',
  'requests.viewApplicants': 'விண்ணப்பதாரர்களைப் பார்க்க ({count})',
  'requests.message': 'செய்தி',
  'requests.messageAccessibility': '{name}க்குச் செய்தி அனுப்பு',
  'requests.assignedCreator': 'உங்கள் படைப்பாளர்',
  'requests.creatorFallback': 'உங்கள் படைப்பாளர்',
  'requests.statusAccessibility': 'நிலை: {status}',
  'requests.empty.title': 'நீங்கள் இன்னும் உதவி கேட்கவில்லை',
  'requests.empty.body': 'நீங்கள் பாதுகாக்க விரும்பும் கதையைச் சொல்லுங்கள்; இளம் படைப்பாளர் ஒருவர் உதவுவார்.',
  'requests.empty.cta': 'உதவி கேளுங்கள்',
  'requests.newRequest': 'புதிய கோரிக்கை',
  'requests.loadError.title': 'உங்கள் கோரிக்கைகளை ஏற்ற முடியவில்லை',
  'requests.loadError.body': 'இணைப்பைச் சரிபார்த்து மீண்டும் முயலவும்.',

  'applicants.headerTitle': 'விண்ணப்பதாரர்கள்',
  'applicants.heading': 'உங்கள் கோரிக்கைக்கான பதில்கள்',
  'applicants.forJob': 'இதற்கு: {title}',
  'applicants.appliedTo': 'விண்ணப்பித்த கோரிக்கை: {title}',
  'applicants.empty': 'இன்னும் யாரும் விண்ணப்பிக்கவில்லை. விண்ணப்பித்ததும் தெரிவிப்போம்.',
  'applicants.allResponded': 'இதுவரை அனைவருக்கும் பதிலளித்துவிட்டீர்கள். புதிய விண்ணப்பதாரர்கள் இங்கே தோன்றுவார்கள்.',
  'applicants.loadError': 'விண்ணப்பதாரர்களை ஏற்ற முடியவில்லை. மீண்டும் முயலவும்.',
  'applicants.rating': '5 இல் {rating} மதிப்பீடு',
  'applicants.noRating': 'புதிய படைப்பாளர் — இன்னும் மதிப்பீடு இல்லை',
  'applicants.messageLabel': 'செய்தி:',
  'applicants.noMessage': 'இந்தப் படைப்பாளர் செய்தி எதுவும் விடவில்லை.',
  'applicants.replyVoice': 'குரலில் பதிலளிக்கவும்',
  'applicants.replyVoiceAccessibility': '{name}க்குக் குரல் பதிலைப் பதிவு செய்',
  'applicants.voiceReplySaved': 'குரல் பதில் இந்தச் சாதனத்தில் சேமிக்கப்பட்டது',
  'applicants.approve': 'ஏற்றுக்கொள்',
  'applicants.approving': 'ஏற்றுக்கொள்கிறது…',
  'applicants.approveAccessibility': 'இந்தக் கோரிக்கைக்கு {name} ஐ ஏற்றுக்கொள்',
  'applicants.reject': 'நிராகரி',
  'applicants.rejectAccessibility': 'இந்தக் கோரிக்கைக்கு {name} ஐ நிராகரி',
  'applicants.notSelected': 'தேர்ந்தெடுக்கப்படவில்லை',
  'applicants.selected': 'தேர்ந்தெடுக்கப்பட்டவர்',
  'applicants.actionError': 'அது நடக்கவில்லை. மீண்டும் முயலவும்.',
  'applicants.messageFrom': '{name} அனுப்பிய செய்தி',

  'voice.title': 'உங்கள் குரலில் பதிலளிக்கவும்',
  'voice.hint': 'மைக்ரோஃபோனைத் தட்டிப் பேசுங்கள். முடிவெடுக்கும் முன் ஒரு கேள்வி கேட்கலாம் அல்லது ஏதாவது சொல்லலாம்.',
  'voice.start': 'பதிவைத் தொடங்கு',
  'voice.stop': 'பதிவை நிறுத்து',
  'voice.recording': 'பதிவு செய்கிறது…',
  'voice.recorded': 'பதிவானது {duration}',
  'voice.recordAgain': 'மீண்டும் பதிவு செய்',
  'voice.save': 'பதிலைச் சேமி',
  'voice.close': 'மூடு',

  'reject.title': 'காரணத்தைத் தெரிவிக்கவா? (விருப்பம்)',
  'reject.reassurance': 'தவிர்ப்பது முற்றிலும் சரியே — நீங்கள் விளக்க வேண்டியதில்லை.',
  'reject.placeholder': 'ஒரு சிறிய, அன்பான குறிப்பு…',
  'reject.field': 'படைப்பாளருக்கான குறிப்பு',
  'reject.skip': 'தவிர்',
  'reject.send': 'அனுப்பு',
  'reject.sending': 'அனுப்புகிறது…',
  'reject.close': 'மூடு',

  'chat.headerTitle': 'செய்திகள்',
  'chat.about': 'தலைப்பு: {title}',
  'chat.intro': 'நீங்கள் {name} ஐத் தேர்ந்தெடுத்தீர்கள். வணக்கம் சொல்லி, பதிவை ஒன்றாகத் திட்டமிடுங்கள்.',
  'chat.replyPlaceholder': 'உங்கள் பதிலைத் தட்டச்சு செய்யுங்கள் அல்லது சொல்லுங்கள்',
  'chat.replyLabel': 'உங்கள் பதில்',
  'chat.send': 'பதிலை அனுப்பு',
  'chat.you': 'நீங்கள்',
};

export const HIRE_STRINGS: Record<AppLocale, HireStrings> = { en, si, ta };

/** BCP-47 tag used for date formatting per locale. */
export const LOCALE_DATE_TAG: Record<AppLocale, string> = {
  en: 'en-GB',
  si: 'si-LK',
  ta: 'ta-LK',
};

/** BCP-47 tag handed to the device speech recogniser per locale, so dictation matches the display language. */
export const LOCALE_SPEECH_TAG: Record<AppLocale, string> = {
  en: 'en-US',
  si: 'si-LK',
  ta: 'ta-LK',
};
